👞 Footer Layout
reworkd/AgentGPT pull request #1019
Opened 2023-07-11 02:27 UTC by jasangill1

## About 

- Want to know what to do for the on hover, current I just took the hover that Joe made for the buttons under the hero title. 
- Maked a very basic list for the footer links started the status button. 
- Let me know oh how you would wan that ehover effects

2023-07-11 02:29 UTC, asim-shrestha commented on next/src/components/landing/FooterLinks.tsx
> +        className="rounded-full bg-transparent text-white/60 transition duration-200 ease-in-out hover:bg-neutral-900 hover:text-neutral-100 focus-visible:bg-neutral-900 focus-visible:outline-none fo
We shouldn't be duplicating these for each button. Lets extract this into a common component and use for each of the links

2023-07-11 02:31 UTC, asim-shrestha commented on next/src/components/landing/Hero.tsx
> +        s
This is making the deployment fail

2023-07-11 03:18 UTC, jasangill1 commented
![image](https://github.com/reworkd/AgentGPT/assets/56135840/78a36c21-d317-487b-a1a7-fab0a889584d)

2023-07-11 04:45 UTC, asim-shrestha commented
A bit sus on mobile

2023-07-11 04:48 UTC, asim-shrestha commented on next/src/components/landing/FooterLinks.tsx
> +      "w-full rounded-full bg-transparent text-white/20 ",
lets use a text-neutral by default. Currently its too dark to see when not hovered

2023-07-11 04:49 UTC, asim-shrestha commented on next/src/components/landing/FooterLinks.tsx
> +const FooterLink = ({ href, children }) => (
Missing typescript types. Your editor should be complaining about this

2023-07-11 04:50 UTC, asim-shrestha commented on next/src/components/landing/FooterLinks.tsx
> +      "w-full rounded-full bg-transparent text-white/20 ",
Also, we can just pass in the `Status` stuff as children as well so that it can be

2023-07-11 22:44 UTC, awtkns commented on next/src/components/landing/FooterLinks.tsx
> +      " focus:outline-none focus:ring-2 focus:ring-white/60 focus:ring-offset-2 focus:ring-offset-transparent"
```suggestion
      "focus:outline-none focus:ring-2 focus:ring-white/60 focus:ring-offset-2 focus:ring-offset-transparent"
```

2023-07-11 22:44 UTC, awtkns commented on next/src/components/landing/FooterLinks.tsx
> +      "w-full rounded-full bg-transparent text-white/20 ",
```suggestion
      "w-full rounded-full bg-transparent text-white/20",
```

2023-07-11 22:44 UTC, awtkns commented on next/src/components/landing/FooterLinks.tsx
> +      " focus:outline-none focus:ring-2 focus:ring-white/60 focus:ring-offset-2 focus:ring-offset-transparent"
nit: Of the mind we shouldn't be using clsx unless there are variables. Instead you can just setup line wrapping.

CLSX is worse for performance and makes it so tw classes are no longer sorted. 

Not a huge issue just something to keep in mind for the future

2023-07-11 22:50 UTC, awtkns commented
<img width="369" alt="Screenshot 2023-07-11 at 3 49 32 PM" src="https://github.com/reworkd/AgentGPT/assets/32209255/10c6490f-d205-48c9-8bdf-938d3987bb28">

The alignment of these need to be consistent

2023-07-11 22:50 UTC, awtkns commented on next/src/components/landing/Hero.tsx
> +        <div className="flex justify-between px-4 md:px-8 lg:px-16">
Similar to the figma design we also need to add the copyright notice

2023-07-11 22:52 UTC, awtkns requested changes
Please address @asim-shrestha's comments and see comments about copyright / alignment of footer items

2023-07-12 00:49 UTC, jasangill1 commented on next/src/components/landing/Hero.tsx
> +        <div className="flex justify-between px-4 md:px-8 lg:px-16">
yes daddy

2023-07-12 00:50 UTC, jasangill1 commented on next/src/components/landing/FooterLinks.tsx
> +const FooterLink = ({ href, children }) => (
typing it daddy

2023-07-12 01:15 UTC, jasangill1 commented
![image](https://github.com/reworkd/AgentGPT/assets/56135840/56b3c396-b77e-44b6-9f0c-54ad14b18866)

![image](https://github.com/reworkd/AgentGPT/assets/56135840/dad5b4ec-adfe-43f8-85d8-a47ac89b3cbe)


adjusted the things in the comments above !! fixed the styling to be more like Figma

2023-07-12 01:52 UTC, merged