chinese-readme
reworkd/AgentGPT pull request #120
Opened 2023-04-14 12:03 UTC by HashCookie

2023-04-14 12:12 UTC, HashCookie commented
> _ No description provided.  没有提供说明。_

Chinese documents were added

2023-04-15 00:43 UTC, asim-shrestha commented
Heyo happy to merge this in, we've just updated the readme so will have to fix the conflicts

2023-04-15 02:14 UTC, Jshen123 requested changes
This seems to be translated by ChatGPT. 

If we are merging this, we should at least address all of these comments.
CC: @asim-shrestha,

2023-04-15 02:14 UTC, Jshen123 commented on docs/zh/README-zh.md
> +
通过矢量数据库来实现长期记忆 🧠
通过 langchain 来实现网络浏览能力 🌐
与网站和人互动 👨‍👩‍👦
通过文档API 实现写作能力 📄
保存代理的运行 💾
用户和身份验证 🔐
通过 Stripe 提供较低限制的付费版本（降低我们的基础设施成本)

即将推出更多功能...

2023-04-15 02:14 UTC, Jshen123 commented on docs/zh/README-zh.md
> +使用 Docker 是在本地运行 AgentGPT 的最简单方法。
> 使用 Docker 是在本地运行 AgentGPT 的最简单方法。

Docker 是在本地运行 AgentGPT 的最简单的方法。

2023-04-15 02:14 UTC, Jshen123 commented on docs/zh/README-zh.md
> +提供了一个方便的设置脚本，帮助你入门。
> 提供了一个方便的设置脚本，帮助你入门。

以下是一个方便的设置脚本

2023-04-15 02:14 UTC, Jshen123 commented on docs/zh/README-zh.md
> +使用提供的设置脚本。
使用以下的设置脚本

2023-04-15 02:14 UTC, Jshen123 commented on docs/zh/README-zh.md
> +1. 叉开这个项目：
创建存储库分支

2023-04-15 02:14 UTC, Jshen123 commented on docs/zh/README-zh.md
> +2. 克隆版本库：
克隆存储库

2023-04-15 02:14 UTC, Jshen123 commented on docs/zh/README-zh.md
> +4. 创建一个 a.**env**文件，内容如下：
使用以下内容创建**env**：

2023-04-15 02:14 UTC, Jshen123 commented on docs/zh/README-zh.md
> +# 下一个Auth配置：
Next Auth 配置

2023-04-15 02:14 UTC, Jshen123 commented on docs/zh/README-zh.md
> +# 你的开放api密钥
你的open api密钥

2023-04-15 02:14 UTC, Jshen123 commented on docs/zh/README-zh.md
> +6. 准备好🥳，现在运行：
准备就绪🥳，现在可以运行了：

2023-04-17 03:14 UTC, Jshen123 commented
Hi @HashCookie thank you for making the PR. We have merged a separate PR here for Chinese Readme
https://github.com/reworkd/AgentGPT/pull/188

2023-04-17 03:14 UTC, closed without merging