feat(env): read variables from .env file
reworkd/AgentGPT pull request #39
Opened 2023-04-12 06:55 UTC by gauravsaini

read vars from env file 
otherwise use the fallback

2023-04-12 07:21 UTC, awtkns commented on src/utils/chain.ts
> +      temperature: process.env.TEMPRATURE  || 0.9,
@gauravsaini thoughts on prefixing this with OPENAI_

2023-04-12 09:06 UTC, gauravsaini commented on src/utils/chain.ts
> +      temperature: process.env.TEMPRATURE  || 0.9,
These `in future` can be with anything (not necessarily OPENAI )
I think AGENTGPT_ would be a better prefix 
Thoughts ?

2023-04-12 11:47 UTC, awtkns requested changes

2023-04-12 11:47 UTC, awtkns commented on src/utils/chain.ts
> +      temperature: process.env.TEMPRATURE  || 0.9,
@gauravsaini my thoughts with the prefix are that in the future we will most likely have multiple model that will be running at once in which case we would need to distinguish between tempratures

2023-04-12 13:33 UTC, mrayonnaise commented
I have been working on something similar to this too. Maybe we can combine efforts? I am adding the MAX_LOOPS as a config item for phase 1 and then adding it as a setting in the UI in phase 2. My work in progress (WIP) is here:
https://github.com/reworkd/AgentGPT/pull/51

2023-04-13 09:28 UTC, gauravsaini commented
@awtkns  : Done

2023-04-13 22:29 UTC, chozzz commented on src/utils/chain.ts
> +      temperature: process.env.OPENAI_TEMPRATURE  || 0.9,
Is it a typo? `OPENAI_TEMPRATURE`?

2023-04-15 11:49 UTC, closed without merging