Feat/drag and drop task window
reworkd/AgentGPT pull request #438
Opened 2023-05-03 02:07 UTC by Jacky-He

2023-05-03 07:28 UTC, awtkns reviewed
Looking good so far, just left a few comments. Amazing work 🚀 

Also seems there is a build error and some merge conflicts.

2023-05-03 07:28 UTC, awtkns commented on prisma/schema.prismae
> +generator client {
This file should not be committed

2023-05-03 07:28 UTC, awtkns commented on prisma/schema.prisma
> +  provider     = "sqlite"
The changes to this file should not be committed :)

2023-05-03 07:28 UTC, awtkns commented on package.json
> +    "@hello-pangea/dnd": "^16.2.0",
Instead of adding another animation library, what are your thoughts on using framer-motion instead as this is already bundled as dependancy. Eg: https://codesandbox.io/s/framer-motion-drag-to-reorder-pkm1k?file=/src/Example.tsx

2023-05-07 02:38 UTC, Jacky-He commented on package.json
> +    "@hello-pangea/dnd": "^16.2.0",
Hi @awtkns thanks for the comments! We think that @hello-pangea/dnd is easier for us to work with for the moment. We do think that "framer-motion" is more flexible and seems to be a cool library to use, so it could be good for a future enhancement task. Does that sound good to you?

2023-05-07 20:18 UTC, Jshen123 requested changes
I think this is a cool idea :) but have some feedbacks and concerns about this PR:

1. From an UI perspective, the order of **Current Tasks**  currently implies a chronological progression. 
a. If we allow drag and drop, we need to decide what the order of  **Current Tasks** is trying to communicate.
b. We also need to design rules and requirements on what type of task can be dragged above other tasks (e.g. we probably shouldn't allow started task to be dragged above a completed task)
2. Right now, it looks like only `tasks` state is being arranged. I think the `messages` state also need to be correctly rearranged to be in sync with reordered tasks.
a. This brings up another question. Should we have this type of mutation for messages? (similar concern as 1, Messages currently serves a chronological log of the agent's activity)
3. I think `reorderTasks` will create issues if run on **automatic mode**. Right now it looks like it's setting the `tasks` state with an in-memory state `updatedTasks`. However, because the `AutonomousAgent` is running in parallel, any task generated by `AutonomousAgent` during the reorder operation will be overwritten.

2023-05-09 14:01 UTC, daga-fam commented
Does this PR include running the tasks manually as well?

2023-06-27 18:12 UTC, closed without merging