Config MAX_LOOPS (and anything else)
reworkd/AgentGPT pull request #51
Opened 2023-04-12 13:33 UTC by mrayonnaise

* Adds scaffolding for generally returning server-side environment variables _selectively_ to the UI via API call
* Adds MAX_LOOPS as new env setting

2023-04-12 20:44 UTC, nicklloyd commented
And this is why I check open PRs before pushing... nice one @mrayonnaise

2023-04-13 02:39 UTC, mrayonnaise commented
> And this is why I check open PRs before pushing... nice one @mrayonnaise

Thanks @nicklloyd!!!

2023-04-13 02:43 UTC, mrayonnaise commented
@awtkns What do you think?

2023-04-13 12:49 UTC, awtkns commented
I have some pending comments that I can't figure out to post through the mobile app. I will hopefully get to this later today 😊

2023-04-13 12:51 UTC, awtkns requested changes

2023-04-13 20:50 UTC, mrayonnaise commented on src/pages/api/settings.ts
> +export default function handler(
My thought is that this will likely be used to communicate other default values/settings to the client beyond just max_loops

2023-04-13 20:51 UTC, mrayonnaise commented on src/pages/index.tsx
> +  const [maxLoops] = React.useState<number>(5);
Good catch - leftover from a prior attempt

2023-04-14 08:03 UTC, awtkns commented on src/pages/api/settings.ts
> +export default function handler(
I think this is probably over engineering for the time being, our hosting costs are quite high. The more client side stuff the better for now

2023-04-14 17:11 UTC, closed without merging